-- 코드를 입력하세요
SELECT I.REST_ID REST_ID, I.REST_NAME REST_NAME, I.FOOD_TYPE FOOD_TYPE, I.FAVORITES FAVORITES,
    I.ADDRESS ADDRESS, round(AVG(R.REVIEW_SCORE),2) as SCORE
    from REST_INFO I inner JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
    where ADDRESS LIKE ('서울%')
    group by REST_ID
    order by SCORE desc, FAVORITES desc;
    