select CAR_ID, round(avg(datediff(END_DATE,START_DATE)+1),1) AVERAGE_DURATION
    from CAR_RENTAL_COMPANY_RENTAL_HISTORY
    group by CAR_ID
    HAVING AVERAGE_DURATION>7.0
    order by AVERAGE_DURATION desc, CAR_ID desc;