SELECT DISTINCT t.ID, t.EMAIL, t.FIRST_NAME, t.LAST_NAME
FROM (
    SELECT d.*, s.CODE
    FROM DEVELOPERS d JOIN SKILLCODES s ON s.NAME IN ('Python', 'C#')
) t
WHERE t.SKILL_CODE & t.CODE != 0
ORDER BY t.ID ASC;